# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: ISL sketchbook
author: Ata Kalirad
#logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

